[tools]
gh = "latest"
jq = "latest"
ripgrep = "latest"
bat = "latest"
fd = "latest"
eza = "latest"
glow = "latest"
dust = "latest"
yazi = "latest"
lazygit = "latest"
gitui = "latest"
delta = "latest"
markdownlint-cli2 = "latest"
