[tasks.update]
description = "Update brew + mise + uv tools and clean up"
run = [
    "brew update",
    "brew upgrade",
    "brew cleanup",
    "mise run alacritty-update",
    "mise upgrade",
    "mise prune",
    "uv tool upgrade --all",
]
