[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/source"
desc = "Go to ~/source"

[[mgr.prepend_keymap]]
on   = [ "g", "k" ]
run  = "cd ~/Desktop"
desc = "Go to ~/Desktop"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd '/Users/glnds/Library/Mobile Documents/com~apple~CloudDocs/Downloads'"
desc = "Go to iCloud Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "o" ]
run  = "cd ~/Documents"
desc = "Go to ~/Documents"
