
# Colors (Cyberdream)
[colors.primary]
background = '#16181a'
foreground = '#ffffff'

[colors.normal]
black =   '#16181a'
red =     '#ff6e5e'
green =   '#5eff6c'
yellow =  '#f1ff5e'
blue =    '#5ea1ff'
magenta = '#bd5eff'
cyan =    '#5ef1ff'
white =   '#ffffff'

[colors.bright]
black =   '#3c4048'
red =     '#ff6e5e'
green =   '#5eff6c'
yellow =  '#f1ff5e'
blue =    '#5ea1ff'
magenta = '#bd5eff'
cyan =    '#5ef1ff'
white =   '#ffffff'

[colors.selection]
background = '#3c4048'
foreground = '#ffffff'

[scrolling]
history = 2000

[window]
startup_mode = "Maximized"
decorations = "Full"
padding = { x = 4, y = 4 }
option_as_alt = "Both"

[font]
size = 14.0
offset = { x = 0, y = 2 }

[font.bold]
family = "MesloLGM Nerd Font"

[font.bold_italic]
family = "MesloLGM Nerd Font"

[font.italic]
family = "MesloLGM Nerd Font"

[font.normal]
family = "MesloLGM Nerd Font"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[220~"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[221~"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
chars = "\u001b[222~"

[[keyboard.bindings]]
key = "M"
mods = "Command|Shift"
action = "ToggleMaximized"

[general]
live_config_reload = false
