[settings]
idiomatic_version_file_enable_tools = ["node", "python"]
not_found_auto_install = true
minimum_release_age = "7d"
minimum_release_age_excludes = ["claude"]

[tools]
node = "26"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
